

############################################## COMMON NAMES WITH DUPLICATES #################################################

names = ['aabidha', 'aali', 'aaliyah', 'aaquella', 'abdul', 'abdullah', 'abeeda', 'abiba', 'abibunnisa', 'abida', 'abidaanjum',
 'abidabegum', 'abidh', 'abidhbasha', 'abidhunnisa', 'abimunnisa', 'adam', 'adham', 'adham bi', 'adil', 'adimbi', 'admbi',
 'admenbi', 'adnan', 'adnshfi', 'afeefa', 'afeez', 'afifa', 'afishn', 'afiya', 'afiyaa', 'afjal', 'afjulunnisa', 'afreed',
 'afreen', 'afreena', 'afridi', 'afrin', 'afroj', 'afroja', 'afroz', 'afroz', 'afsana', 'afsar', 'afsarunnisa', 'aftab',
 'aftharulla', 'afzal', 'afzul', 'ahamed', 'ahmad', 'ahmad', 'ahmed', 'aisha', 'ajara bi', 'ajarbe', 'ajarbi', 'ajaruddin',
 'ajeej', 'ajeemunnisa', 'ajimoon', 'ajimunnisa', 'ajjumun', 'ajmathullah', 'akbar', 'akbar basha', 'akbar shahineas',
 'akbarbi', 'akheela', 'akhtarjajan', 'akhter', 'akramunnisa', 'akramunnisha', 'aksa', 'aktarunnisa', 'akthar', 'aktharunnisa',
 'aktharunnisha', 'alam', 'alee', 'ali', 'ali', 'alia', 'alisha', 'aliya', 'amin', 'amina', 'anjum', 'ansar', 'ansarbi',
 'ansari', 'apsarbaji', 'apsarunnisa', 'aqil', 'arif', 'arifa', 'ariz', 'arman', 'arshad', 'arshia', 'arshiya', 'arzoo',
 'asif', 'asiya', 'aslam', 'asma', 'atahar', 'aterunnisa', 'atharunnisa', 'atiya', 'attaruneesa', 'ayesha', 'azahar', 'azas',
 'azeej', 'azeem', 'azees', 'azeez', 'azeeza', 'azgar', 'azgarali', 'azhar', 'azharuddin', 'azhghar', 'azimoon', 'azimuddin',
 'azimunisa', 'azimunnisa', 'azivali', 'aziz', 'azma', 'azmal', 'azmathullah', 'azmathunnisa', 'azmatulla', 'azmoon', 'azziz',
 'azzmal', 'babar', 'baig', 'basha', 'basha', 'basharat', 'bashir', 'basit', 'begam', 'begam', 'begum', 'bilal', 'bilquis',
 'dilshad', 'dina', 'fahim', 'faisal', 'farah', 'fareed', 'farheen', 'farida', 'fariha', 'farkhanda', 'fatemeh', 'fatima',
 'fatimah', 'fayaz', 'fazila', 'feroz', 'feroze', 'fiza', 'ghulam', 'gulzar', 'hadi', 'hadiya', 'haider', 'hamza', 'hana',
 'hasan', 'hbibunnisha', 'hejira', 'hepsiba', 'hossain', 'huda', 'hussaian', 'hussain', 'hussaina', 'hussainaiah', 'hussainbe',
 'hussainbee', 'hussainbi', 'hussaindi', 'hussainhi', 'hussaini', 'hussane', 'hussebharani', 'hussein', 'hussen', 'hussenamma',
 'hussenu', 'ibrahim', 'ilyas', 'iman', 'imran', 'imtiaz', 'inaya', 'iram', 'irfan', 'isak', 'ismail', 'ismat', 'jabeen',
 'jabir', 'jafar', 'jamal', 'jami', 'jamil', 'jamila', 'jani', 'javed', 'jawad', 'junaid', 'kamran', 'kareem', 'karim',
 'kausar', 'khadija', 'khair', 'khaja', 'khalid', 'khan', 'khan', 'khan', 'kiran', 'kouser', 'layla', 'leila', 'm d', 'mahammad',
 'mahmad', 'maimoona', 'malik', 'mariam', 'md', 'mehnaz', 'mohammad', 'mohammed', 'mohammed', 'mohd', 'mohd', 'mohemmad',
 'mohmad', 'mohmmad', 'muhammad', 'mujeeb', 'musa', 'mushtaq', 'mustafa', 'naaz', 'nabil', 'nadia', 'nafisa', 'naheed',
 'naima', 'najib', 'najla', 'najma', 'nashit', 'nashra', 'nasir', 'nasreen', 'naveed', 'naveeda', 'nawab', 'nazia', 'neha',
 'noor', 'nouf', 'nour', 'nusrat', 'omar', 'parveen', 'pasha', 'qais', 'qamar', 'qasim', 'rabia', 'rafi', 'rahim', 'rahman',
 'rameez', 'rashid', 'rashida', 'rehana', 'rizwan', 'rizwana', 'rukaiya', 'rukhsana', 'rukhsar', 'saba', 'sabah', 'sabira',
 'safi', 'safiya', 'sahar', 'saheb', 'saher', 'sahira', 'saida', 'saieed', 'saif', 'saifullah', 'saima', 'salam', 'salima',
 'salma', 'salman', 'samina', 'samira', 'sana', 'sara', 'sarina', 'sarwar', 'sayed', 'sayyad', 'shabnam', 'shafi', 'shahida',
 'shaik', 'shaik', 'shakir', 'shameem', 'shazia', 'shehanaaz', 'shehnaz', 'shek', 'shoaib', 'sikandar', 'sk', 'sohail', 'sultan',
 'sulthan', 'sulthana', 'sumaya', 'syed', 'tabassum', 'tabasum', 'tahir', 'talat', 'talha', 'tanveer', 'tanzila', 'tariq',
 'thabassum', 'tunnisa', 'uddin', 'uddin', 'ullah', 'umar', 'wahab', 'waheed', 'wahid', 'waseem', 'yahya', 'yaqub', 'yasir',
 'yasmeen', 'yasmin', 'yasmine', 'younus', 'yumna', 'yusuf', 'zafran', 'zaheer', 'zahra', 'zainab', 'zakariya', 'zarina',
 'zeba', 'zeenat', 'zoya', 'zubaida', 'zubair', 'zubeer', 'zuberia', 'zulekha', 'zulfikar', 'zulfikhar', 'zuned',   'ajimun','ajinunbi','azeeka','azeezuddin','azizuddin','azeejun','azizunnisa','ajimun','azeeka','azijan',
    'Khadhar','Aabeda','Abjarunnisa','Abzal','Abjulun','Abzulun','Abzel','Abdu Sami','Abdunisha','SkAbdur Rahaman',
    'Abdula','Abdulah','Abdulu','Abdulu Farzana Begum','Abdhul','Abdulrehaman','Abdulrahaman','Abdulkaram',
    'Abdulkarim','Abdulkhadar','Abdulkhadar','Abdulgaffar','Abdulbasit','Abdulrahaman','Abdulraheem','Abdulrahim',
    'Abdulrahem','Abdulla','Rahaman','rehaman','Abdulsamad','Abdulsalam','Abdulhak','Abdulhannan','Abdulhamid',
    'Abdulhuq','Abdus Sattar','Abdhul','Abdual','Abbas','Abraham','Abhierudien','Amanullah','Amanulla','Amanullah',
    'Aman Basha','Amanulla','Amanulla','Amanullah','Aminabi','Aminudinn','Amirunnisa','Amidunnisa','Ameed','Ameed',
    'Ameena','Ameena Bi','Aminabee','Aminuddin','Ameenul Ahad','Ameenullah','Ameen','Aameenkausar','Aminroshan',
    'Ameera','Amira','Amira','Ameeruddinsha','Ameerunisa','Ameerunisa','Ameerun','Amirun','Ameerun','Amirunnisa',
    'Ameerunnisa','Ameeroon','Ameer','Ameer Bi','Ameer Jaani','Ameer Jhany','Ameer P','Ameer Basha','Ameer Mallik',
    'Ameerbasha','Ameerbhasha','Amunalla','Amenabi','Ameeruniisa','Amerunisa','Amerun','Ameroon','Amerun','Amreen',
    'Ayaaz','Ayaz Ahmad','Ayaan','Ayashaparvin','Ayub','Ayub Apsar','Ayeasha','Sk Ayeshaparveen','Arafath','Aripunnisa',
    'Arifunnisa','Arifunnisa Begum','Arifulla','Arifoon','Areefa','Areef','Arief','Arief','Areef Bhasha','Arefa',
    'Arshin','Arsheen','Arshatulla','Alimbi','Alima','Alimun','Alimoon','Alim','Aliyabi','Aliahmed','ahmed','ali',
    'Alii Sha','Alikhan','Aleepha','Alibasha','Aleem','Aleem Bi','Alishabegum','Alishaida','Althaf','Altaf',
    'Altaf Ahammad','Altaf Basha','Alfunsamma','Almanesh Sharief','Almas Ruhi','Alla','Bakshu','Allabi','Sattar',
    'Allanabi','Allabi','Allah','Rahaman','Allabakshu','Allabaksh','Allabashu','Allabukshu','Allabhakshu',
    'Allabhi','Allavali','Allauddin','Altaf','Saheb','Allimbi','Allibeg','Allisa','Allisaheb','Allauddin','Alshifa',
    'Ashabegam','Ashahar','Ashirifun','Ashraf','Ahammad','Ashrifun','Ashrifunnisa','Ashadullah','Ashafuun','Ashabi',
    'Ashabee','Ashabibi','Ashabe','Asharafun','Ashifun','Ashima','Ashia','Ashiya','Ashirifun','Asheef','Funnisa',
    'Ashkruka','Ashfiya','Ashmad','Ashma','Ashrath','Ashrapunnisa','Ashraf','Ashrafun','Ashrafunnisa','Ashrafunnisabegam',
    'Ashrifunnina','Ashrifunnisa','Ashrufun','Asadulla','Asad','Asaabee','Asalatha','Asalam','Asifun','Assif',
    'Asima','Asimun','Asimunnisa','Asim','Aseena','Aseem','Asfhak','Asmatara','Asmathunisa','Asmathunnisa',
    'Asmatulla','Asmath','Asmathulla','Asmeen','Asya','Asraf','Asrar','Asripun','Asrifunisa','Asrifun','Asrifoon',
    'Ahamadalisha','Ahamadunnisa','Ahamad','Ahamed','Ahamdulla','Ahammudunisa','Ahammadunnisha','Ahammad','Ahammed',
    'Ahmad','Ahmmad','Ahmmed','Rasool','Shakeel','Ahamed','Sharifmd','Ahrone','Aakif','Aaqil','Ashraf','Azad',
    'Adambasha','Adambi','Aadambi','Adam','baji','Vali','Shafi','Shafee','Shafi','Shaphi','Adambee','Adamshaffi',
    'AdamshaifAdam','Adamshafi','Aadambi','Adamsaheb','Adimbi','Adimunnisa','Aafiya','Aafiha','Aftharunnisa',
    'Aafrin','Afrin','Aafrin','Firolose','Aafreen','Afreen Sultana','Affrozia','Affrose','Aabida','Aabidun',
    'Ayisha','Aysha','Aayeesha','Aathaf','Aatif','Aeesha','Ayeesha','Aaesha','Aiesha','Sumer','Aayesha','Ayesh',
    'Ayeshbegam','Aaysha','Aarifa','Arifahamed','Arifha','Arifha','Basha','Asha Bi','Ashabegum','Ashabhi',
    'Ashiripun','Ashirfun','Aasisha','Asher','Aashiqllaahi','Asifa','Ahmad','Aseef','Inthaz','Inthiyaz','Intiyaz',
    'Imtiyaz','Intiaz','Intiyaz','Izak','Izaz','Ahamed','Nazeer','Inayath','Intyaz Bi','Far Jan','Iffath','Khaleelulla',
    'Ibraheem','Ibrheem','Ibham','Shabrooz','Imam','Imambi','Imamvali','Imambee','Imambhi','Imamsa','Imamsaa',
    'Imamsaheb','Imamunnisa','Sharief','Saheb','Imam-Bi','Irfana','Irfhan','Irfaan','Irphan','Irshad','Irshaad',
    'Mohinuddin','Iliyaz','Ilahi','Eliyaz','Iliyas','Eliyas','Isavalishaik','Isavali','Istakhar','Istikhar',
    'Islam','Saleem','Esoobvali','Habeeba','Benhar','Ummar','Faruq','Faruk','Ummarvali','Mujahid','Usman',
    'Sk Usman','Mahamed','Ussanbee','Fayaz','EpsibaObaidulla','Kathiza','Kathija','Kadharbi','Kadir','Kadeer',
    'Kadhar','Kabeera','Kabeer','Kabirsha','Kamarun','Kamarunnisa','Kamarjaha','Kamarjahan','Kamarnissa','Karima',
    'Karimuddin','Karimunisabi','Karimune','Karimun','Ephraim','Ebinezer','Ebenezer','Emamsa','Emambi','Erfan',
    'Salam','Esubee','Esubbi','Esmavali','Eliyaz','Aesha','Karimunni','Karimunnisa','Karimunny','Karimula',
    'Karimulla','Karimullah','Karimoon','Karishmabegam','Kareena','Karima','Kareema','Karimabi','Karimuddin',
    'Karimunesa','Karimun','Karimunisha','Kareemun','Kareemunnisa','Bebi','Kareemullah','Karimullah','Karimoon',
    'Kareemoon','Karemoonbi','Karemunnisa','Kalsanbi','Kulsunbee','Sharief','Kasim','Kahderbee','Kahmeera',
    'Kajabee','Kajavali','Kafeytulla','Kalebu','Kalebude','Kalesha','Kaleshaalikhan','Kaleshavali','Kashim',
    'Bishek','Kashimbe','Kashif','Kasim','Kasimkhan','Kasimbee','Kasimbe','Kasimsha','Kaasim','Kasembee',
    'Qureshjahan','Kurshid','Kurshib','Kursheed','Kurshed','Kulusumbi','Kulusom','Kulshani','Kulsum','Kushim',
    'Kusheeda','Kodanabi','Koushar','Kousar','Kouser','Kowsar','Kowser','Queeni Leena','Kmusmbunisa','Khajanasrin',
    'Khajabi','Khazabi','Khajabee','Khajamohiddin','Khajaramthulla','Khajar','Khazana','Khjavali','Khazeena',
    'Khajeer','Khadam','Khadenunnisa','Khatija','Khathijathul','Khatizaha','Khatija','Khateeja','Khateeza',
    'Khathija','Khatija','Khathija','Khateeza','Khatiza','Khatijaabi','Khatijabee','Khatijabi','Khathijabi',
    'Khateeb','Khatunbi','Khatun','Khathum','Khadar','Khadarbi','Khadeejatul','Khadeer','Khadir','Khader',
    'Khaddar','Khadhar','Khamarunnisa','Khamaroon','Khamar','Jahan','Khmar Jhan','Khamarjaha','Khamarzahan',
    'Khamurin','Khamurunbi','Khamruddin','Khamrun','Qhamrun','Khamrunnisa','Khamroon','Mohiddin','Khayyum',
    'Kharimun','Kharimulla','Kharishma','Kharoon','Khalil','Khaleem','Khalida','Khalilulla','Khaleel','Khalil',
    'Khaleel','Khalisha','Khalel','Sajjad','Rehman','Khashimbi','Khasim','Khasimkhan','Khasimbi','Khasimbee',
    'Khaza','Ahamad','Shareef','Khajabi','Khajabhi','Khajamunir','Khajamohiddin','Khajavali','Khajawali','Khatoon',
    'Khadarunnisha','Khadarunnisa','Khadar','Khader','Khadhar','Mastan','Mohiuddin','Mohiddin','Sharfuddin',
    'Khadarnisahab','Khaderba','Khadarbasha','Khaderbasha','Khadarbi','Khadarbee','Khanam','Fathima','Khashim',
    'Khashifa','Khasim','Khasimbabu','Khasimbee','Khasimbe','Khasimbee','Khasimbe','Khasiya','Khasira','Khaseem',
    'Khasima','Khijarunnisa','Khizer','Ayub','Khiyaz','Khirun','Khiraunnisa','Tasneem','Khutija','Khudavan',
    'Rabbani','Khudba','Khureeshid','Khureshi','Khurshid','Khursheed','Khurshida','Khushi','Khushumath','Khusboo',
    'Khedeer','Khaiser','Khaim','Khyruniassa','Khairun','Khairunnisa']


print(len(names))

# Sample list of names
# Remove duplicates using set
unique_names = set(names)

# Strip and lowercase the names
cleaned_names = [name.strip().lower() for name in unique_names]

print(cleaned_names)
print(len(cleaned_names))

###################################################### NAMES WITH OUT DUPLICATES ######################################################

cl = ['samina', 'alisha', 'farheen', 'abidh', 'afroj', 'ajmathullah', 'sayyad', 'fiza', 'salma', 'bashir', 'junaid',
      'sarina', 'nouf', 'hussain', 'salima', 'nabil', 'akhtarjajan', 'shehnaz', 'younus', 'qamar', 'azzmal', 'hussaindi',
      'azharuddin', 'asiya', 'azimunisa', 'shazia', 'nazia', 'sulthana', 'azimunnisa', 'javed', 'jamila', 'tunnisa', 'leila',
      'imtiaz', 'ansari', 'sikandar', 'zakariya', 'zuned', 'rafi', 'ajarbe', 'rehana', 'fatimah', 'azas', 'nawab', 'adimbi',
      'sabira', 'shafi', 'atahar', 'sk', 'hussenamma', 'ismat', 'shahida', 'uddin', 'nasreen', 'azeej', 'sara', 'babar',
      'basharat', 'nusrat', 'talat', 'sarwar', 'qais', 'afjal', 'azgar', 'abiba', 'jabeen', 'fatima', 'admbi', 'abidabegum',
      'hana', 'tabassum', 'zaheer', 'aisha', 'aaquella', 'fayaz', 'ibrahim', 'md', 'khalid', 'sana', 'zainab', 'sahira',
      'arshad', 'aterunnisa', 'fazila', 'kausar', 'gulzar', 'zulekha', 'abidhbasha', 'afjulunnisa', 'zulfikar', 'abdullah',
      'alam', 'saida', 'ajarbi', 'abidhunnisa', 'afroz', 'azimuddin', 'shameem', 'amin', 'imran', 'aliya', 'iman', 'hussane',
      'afsar', 'sabah', 'farah', 'afridi', 'saieed', 'akramunnisha', 'mehnaz', 'anjum', 'shakir', 'akheela', 'adnan', 'rahim',
      'apsarbaji', 'arshiya', 'aabidha', 'ahamed', 'aaliyah', 'mohammad', 'neha', 'ismail', 'azivali', 'abimunnisa', 'kamran',
      'afishn', 'mahammad', 'abdul', 'najib', 'huda', 'tahir', 'yasmin', 'qasim', 'hussaina', 'hossain', 'haider', 'feroz',
      'talha', 'arifa', 'shehanaaz', 'hussaini', 'rukaiya', 'jami', 'naveed', 'afsana', 'hasan', 'abidaanjum', 'rashida', 'adam',
      'azma', 'saif', 'aksa', 'layla', 'rashid', 'zeenat', 'rukhsana', 'azgarali', 'shek', 'begum', 'afiyaa', 'maimoona', 'malik',
      'jamal', 'inaya', 'azhar', 'abibunnisa', 'afrin', 'azhghar', 'hamza', 'ansarbi', 'ahmad', 'amina', 'azziz', 'shaik', 'jawad',
      'atharunnisa', 'zulfikhar', 'akthar', 'musa', 'hussainhi', 'nour', 'afeefa', 'abeeda', 'arif', 'mohd', 'pasha', 'akbarbi',
      'ilyas', 'fareed', 'aslam', 'kouser', 'adham', 'aktarunnisa', 'azmal', 'azeez', 'jani', 'naaz', 'hussen', 'azeem', 'aziz',
      'akhter', 'ali', 'yasmine', 'mustafa', 'hussein', 'baig', 'safi', 'asma', 'rameez', 'isak', 'wahab', 'sayed', 'rizwana',
      'faisal', 'saba', 'aqil', 'waseem', 'yahya', 'yaqub', 'yumna', 'aftharulla', 'afiya', 'azees', 'najla', 'nadia', 'tariq',
      'salman', 'afzul', 'yasir', 'hussainbee', 'afroja', 'shoaib', 'akbar', 'nafisa', 'ajimoon', 'yasmeen', 'samira', 'aftab',
      'azimoon', 'asif', 'begam', 'saher', 'aktharunnisha', 'parveen', 'khan', 'thabassum', 'alia', 'kareem', 'ayesha', 'nashit',
      'hussainbi', 'zoya', 'noor', 'omar', 'bilquis', 'jamil', 'zuberia', 'akbar shahineas', 'attaruneesa', 'farida', 'bilal', 'dina',
      'ajara bi', 'afeez', 'adham bi', 'ullah', 'umar', 'zafran', 'akramunnisa', 'mohmmad', 'adil', 'tanveer', 'afreena', 'azeeza',
      'afifa', 'ghulam', 'ajeemunnisa', 'jafar', 'sahar', 'adnshfi', 'fariha', 'ariz', 'hussainbe', 'arshia', 'arzoo', 'sohail',
      'zubeer', 'safiya', 'muhammad', 'rabia', 'basha', 'atiya', 'naheed', 'farkhanda', 'rizwan', 'zahra', 'hejira', 'hussaian',
      'afreen', 'dilshad', 'hadiya', 'mariam', 'rukhsar', 'alee', 'ajeej', 'afzal', 'hbibunnisha', 'basit', 'ajjumun', 'ansar',
      'feroze', 'ajimunnisa', 'saima', 'najma', 'saheb', 'tabasum', 'ajaruddin', 'hussenu', 'jabir', 'sulthan', 'zeba', 'm d',
      'aali', 'tanzila', 'khadija', 'zubair', 'afreed', 'khair', 'sultan', 'azahar', 'wahid', 'mohammed', 'sumaya', 'azmoon',
      'akbar basha', 'afsarunnisa', 'hussebharani', 'admenbi', 'apsarunnisa', 'fatemeh', 'iram', 'kiran', 'yusuf', 'nashra',
      'ahmed', 'zarina', 'mahmad', 'irfan', 'aktharunnisa', 'mujeeb', 'naveeda', 'saifullah', 'mushtaq', 'azmathullah', 'arman',
      'khaja', 'naima', 'shabnam', 'salam', 'azmathunnisa', 'syed', 'mohemmad', 'nasir', 'abida', 'hussainaiah', 'waheed', 'rahman',
      'karim', 'fahim', 'zubaida', 'azmatulla', 'hepsiba', 'hadi', 'mohmad']

# cls = sorted(cl)
# print(cls)

####################################################333333 COMMON NAMES IN ALPHABETICAL ORDER ##################################################

updated_names = ['aabidha', 'aali', 'aaliyah', 'aaquella', 'abdul', 'abdullah', 'abeeda', 'abiba', 'abibunnisa', 'abida', 'abidaanjum',
       'abidabegum', 'abidh', 'abidhbasha', 'abidhunnisa', 'abimunnisa', 'adam', 'adham', 'adham bi', 'adil', 'adimbi', 'admbi',
       'admenbi', 'adnan', 'adnshfi', 'afeefa', 'afeez', 'afifa', 'afishn', 'afiya', 'afiyaa', 'afjal', 'afjulunnisa', 'afreed',
       'afreen', 'afreena', 'afridi', 'afrin', 'afroj', 'afroja', 'afroz', 'afsana', 'afsar', 'afsarunnisa', 'aftab', 'aftharulla',
       'afzal', 'afzul', 'ahamed', 'ahmad', 'ahmed', 'aisha', 'ajara bi', 'ajarbe', 'ajarbi', 'ajaruddin', 'ajeej', 'ajeemunnisa',
       'ajimoon', 'ajimunnisa', 'ajjumun', 'ajmathullah', 'akbar', 'akbar basha', 'akbar shahineas', 'akbarbi', 'akheela', 'akhtarjajan',
       'akhter', 'akramunnisa', 'akramunnisha', 'aksa', 'aktarunnisa', 'akthar', 'aktharunnisa', 'aktharunnisha', 'alam', 'alee', 'ali',
       'alia', 'alisha', 'aliya', 'amin', 'amina', 'anjum', 'ansar', 'ansarbi', 'ansari', 'apsarbaji', 'apsarunnisa', 'aqil', 'arif',
       'arifa', 'ariz', 'arman', 'arshad', 'arshia', 'arshiya', 'arzoo', 'asif', 'asiya', 'aslam', 'asma', 'atahar', 'aterunnisa',
       'atharunnisa', 'atiya', 'attaruneesa', 'ayesha', 'azahar', 'azas', 'azeej', 'azeem', 'azees', 'azeez', 'azeeza', 'azgar',
       'azgarali', 'azhar', 'azharuddin', 'azhghar', 'azimoon', 'azimuddin', 'azimunisa', 'azimunnisa', 'azivali', 'aziz',
       'azma', 'azmal', 'azmathullah', 'azmathunnisa', 'azmatulla', 'azmoon', 'azziz', 'azzmal', 'babar', 'baig', 'basha',
       'basharat', 'bashir', 'basit', 'begam', 'begum', 'bilal', 'bilquis', 'dilshad', 'dina', 'fahim', 'faisal', 'farah',
       'fareed', 'farheen', 'farida', 'fariha', 'farkhanda', 'fatemeh', 'fatima', 'fatimah', 'fayaz', 'fazila', 'feroz',
       'feroze', 'fiza', 'ghulam', 'gulzar', 'hadi', 'hadiya', 'haider', 'hamza', 'hana', 'hasan', 'hbibunnisha', 'hejira',
       'hepsiba', 'hossain', 'huda', 'hussaian', 'hussain', 'hussaina', 'hussainaiah', 'hussainbe', 'hussainbee', 'hussainbi',
       'hussaindi', 'hussainhi', 'hussaini', 'hussane', 'hussebharani', 'hussein', 'hussen', 'hussenamma', 'hussenu', 'ibrahim',
       'ilyas', 'iman', 'imran', 'imtiaz', 'inaya', 'iram', 'irfan', 'isak', 'ismail', 'ismat', 'jabeen', 'jabir', 'jafar', 'jamal',
       'jami', 'jamil', 'jamila', 'jani', 'javed', 'jawad', 'junaid', 'kamran', 'kareem', 'karim', 'kausar', 'khadija', 'khair', 'khaja',
       'khalid', 'khan', 'kiran', 'kouser', 'layla', 'leila', 'm d', 'mahammad', 'mahmad', 'maimoona', 'malik', 'mariam', 'md', 'mehnaz',
       'mohammad', 'mohammed', 'mohd', 'mohemmad', 'mohmad', 'mohmmad', 'muhammad', 'mujeeb', 'musa', 'mushtaq', 'mustafa', 'naaz', 'nabil',
       'nadia', 'nafisa', 'naheed', 'naima', 'najib', 'najla', 'najma', 'nashit', 'nashra', 'nasir', 'nasreen', 'naveed', 'naveeda', 'nawab',
       'nazia', 'neha', 'noor', 'nouf', 'nour', 'nusrat', 'omar', 'parveen', 'pasha', 'qais', 'qamar', 'qasim', 'rabia', 'rafi', 'rahim', 'rahman',
       'rameez', 'rashid', 'rashida', 'rehana', 'rizwan', 'rizwana', 'rukaiya', 'rukhsana', 'rukhsar', 'saba', 'sabah', 'sabira', 'safi', 'safiya',
       'sahar', 'saheb', 'saher', 'sahira', 'saida', 'saieed', 'saif', 'saifullah', 'saima', 'salam', 'salima', 'salma', 'salman', 'samina', 'samira',
       'sana', 'sara', 'sarina', 'sarwar', 'sayed', 'sayyad', 'shabnam', 'shafi', 'shahida', 'shaik', 'shakir', 'shameem', 'shazia', 'shehanaaz',
       'shehnaz', 'shek', 'shoaib', 'sikandar', 'sk', 'sohail', 'sultan', 'sulthan', 'sulthana', 'sumaya', 'syed', 'tabassum', 'tabasum', 'tahir',
       'talat', 'talha', 'tanveer', 'tanzila', 'tariq', 'thabassum', 'tunnisa', 'uddin', 'ullah', 'umar', 'wahab', 'waheed', 'wahid', 'waseem',
       'yahya', 'yaqub', 'yasir', 'yasmeen', 'yasmin', 'yasmine', 'younus', 'yumna', 'yusuf', 'zafran', 'zaheer', 'zahra', 'zainab', 'zakariya',
       'zarina', 'zeba', 'zeenat', 'zoya', 'zubaida', 'zubair', 'zubeer', 'zuberia', 'zulekha', 'zulfikar', 'zulfikhar', 'zuned']

# print(len(updated_names))
